object Versions {
    const val coreKtx = "1.8.0"
    const val appCompat = "1.4.2"
    const val material = "1.6.1"
    const val hilt = "2.42"
    const val room = "2.4.2"
    const val constraint = "2.1.4"
    const val viewModel = "2.4.1"
    const val navigation = "2.4.2"
    const val preference = "1.2.0"
    const val googleServices = "4.3.10"
    const val gson: String = "2.8.6"
    const val retrofit = "2.9.0"
    const val ok_http = "4.7.2"
    const val coil = "1.4.0"
    const val rxJava = "2.7.2"
}